### ISSUE TITLE
Integrate login mutations in Redux actions

### ISSUE THREAD

**Issue by dfernandezm** [dfernandezm/moneycol#170]
Once #162 is completed, the current login form should use the GraphQL mutations to login instead of the Firebase library in the frontend. This is the first phase towards replacing Redux too.

- [x] How to manage a session in server (token/refreshToken/currentUser). Read Firebase doc. Will use temporary memory/disk cache. Should use Firestore to persist as we want to avoid using Firebase client in frontend. Created #180 
- [x] How to ensure user re-logged in on page refresh as it is now (verify) Created #177
- [x] Should redirect to login when clicking in protected route #178 
- [x] Should allow accessing login page/form always, even when already logged in #179 
- [x] In server GQL, ensure token is not validated for login/logout, but only for protected queries/mutations
- [x] Ensure that other user's tokens are not interfering or returned (isolation of auth) [create issue to check]
- [x] Remove Firebase libraries from frontend
