### ISSUE TITLE
Basic user session management

### ISSUE THREAD

**Issue by dfernandezm** [dfernandezm/moneycol#185]
This is a group of tasks related to #180 and the fact that Firebase Auth client cannot (by design choice) be used in the frontend and it's instead wrapped in the GraphQL server.

This is an interim solution that will work for initial version. A more complete and proper, full fledged solution including frontend storage would be the one outlined in #154.

The initial requirements would be the following: 

- [x] One session from one place is reused
- [x] Restarting or changing servers and the user is still logged in (avoid session stickiness) #180 
- [x] Authentication state persistence across server restarts #180 
- [x] Keep refresh token in Firestore once issued, reissue new tokens from it - #187 
- [x] Revoke refresh token - #187
- [x] Avoid having a valid token after logout - custom lockout model for non-expired tokens #181 
- [x] Test protected and unprotected GQL routes (token validations for Collections API ahead of calling, not token requirement for logout, login, verify) 
- Official docs https://firebase.google.com/docs/auth/admin/manage-sessions

**Comment by gchristov** [comment]
This is quite similar to the way Graffitab works for Facebook login - one user is linked to many external providers and each provider has the tokens etc.

Sounds like you want to have a fully customized login style, meaning no reliance on firebase auth SDK. Not sure how this will work in the client apps tho because the SDKs are already made to integrate nicely with eachother - for example logging in with any of the supported providers gives you the same AuthUser which you then pass to Firebase SDK and it handles the rest. 

In your case you'd have to build all custom logins yourself and then pass the tokens to your server for storage. Unless you can somehow use the provided auth flows from the client SDKs and then extract the tokens from the AuthUser and pass them to the server, but this needs research...

**Comment by gchristov** [comment]
After a quick search, you get this when logging in with the clients: 
https://firebase.google.com/docs/reference/android/com/google/firebase/auth/AuthResult

From there you can use `getUser()` to obtain:
https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseUser

Then with the FirebaseUser you take:
https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseUser#getIdToken(boolean)

And then you can send the token to your server. From AuthResult you can also find out the provider with which the user signed in which should complete your flow I believe.

**Comment by gchristov** [comment]
After that it should be the client's job to detect if it's logged in or not i think. Server shouldn't keep that state. Clients should send some kind of session token which gets validated on the server side, could be set as a cookie or jwt or similar.

**Comment by dfernandezm** [comment]
@8masterofpuppets8 I think a v1 of this has been done, will catch up on it.
