### ISSUE TITLE
Complete registration workflow with Firebase (email/password) definition

### ISSUE THREAD

**Issue by dfernandezm** [dfernandezm/moneycol#206]
- [x] Investigate how to handle default user email creation (welcome email) and create issue on how to customize further (#207 )
- [x] Define React component to land the verification link from email (#208)
   - This page should use the query parameters to verify the email (custom in our backend)
   - React should delegate into GQL for performing the validation Server side (no firebase in FE)
- [x] Define new task for React form/container component (#211)
  - https://gitlab.com/evelog/everlog.gitlab.io/blob/master/src/actions/auth.js
  - Signup: https://github.com/mui-org/material-ui/blob/master/docs/src/pages/getting-started/templates/sign-up/SignUp.js
