### ISSUE TITLE
Google Login: complete

### ISSUE THREAD

**Issue by dfernandezm** [dfernandezm/moneycol#240]
- [x] Complete frontend, organise logic - done in #236 
- [x] Complete backend TODOs - done in #237 
- [x] Backend TODO: should check if this user is already logged in in our system and/or with which provider (use email to check) - done
- [x] Backend TODO: this code is copied from loginWithEmail - avoid copied code - done
- [x] The user that has login with Google cannot change or reset their password and have limited data in their profiles - New issue not done #253 
- [x] Backend TODO: error handling, need to send specific error for this code: `auth/invalid-credential message: ID Token issued at {} is stale to sign-in` - new issue #256 
- [x] Check in other sites if setting failures on Google error is required (test failing google login) - #258
- [ ] Test all login/crud flows once deployed - end of sprint
