### ISSUE TITLE
Upgrade to Micronaut 3.x collections-api

### ISSUE THREAD

**Issue by dfernandezm** [dfernandezm/moneycol#340]
# Task

Story: https://moneycol.atlassian.net/browse/MON-198

Upgrade the `collections-api` module to Micronaut 3.x

# Acceptance criteria

- [x] Tests pass
- [x] Container builds locally with `jib`
- [x] Status endpoint can be invoked locally
- [x] README is updated

# Definition of Done
1. - [x] Current tests pass
2. - [x] New tests added
3. - [x] Pull Request and self review
4. - [ ] Clean build 
5. - [x] Parent story linked

# Related Tasks

- Upgrade to Micronaut 3.x the remainder of modules
- JIRA: https://moneycol.atlassian.net/browse/MON-198
